### PR TITLE
Added LFO phase setting.

### PR DESCRIPTION
**Pull request by libesz**
Implements: #3

### CODE REVIEW

**Comment by JordanAceto** [comment]
Very cool, thanks for looking into this!

A couple things:

1. Can you update the doctring to be more explicit about what the input represents? It looks like we are passing a unitless number where 1.0 represents 2pi. I think in general this is fine, because then we don't need to do any extra work to normalize radians. But it could be more clear in the docstring that if we pass in 1.0 that this represents one cycle. I could also be convinced that the phase parameter should be in radians, I'm not 100% convinced either way yet.
2. I think it should be legal to pass in any floating point number, the input should not be limited to [0.0, 1.0]. If we pass in 2.0 then this is two cycles, 3.5 results in 7pi, etc. I think your code already handles this, but the docstring implies that the legal input range is restricted.
3. I think we should also allow negative phase inputs, but I have not thought about if the existing code will handle this well. Reason for wanting negative phase: for through-zero modulation. This might just mean abs'ing the phase in the phase accumulator module, I would need to think about it for a sec.
4. I don't think the `phase % 1.0` belongs in the LFO module, the phase accumulator module should handle whatever you throw at it without worrying about sanitizing first.
5. Can you add a couple tests? Like if we pass in 0.25 from a reset condition we'd expect the sine and triangle outputs to be near 1.0, stuff like that. -2.0 takes us back to the beginning... A few tests that leave us confident that all phase inputs result in reasonable LFO state. Any phase accumulator module tests should be very straightforward.

Phew that's a lot of stuff. If you just want to use it as-is and not bother with the above, that's fine too. It looks like your changes already handle most of what you'd want it to do. The above is just my wish-list that I would add if I had infinite time. I have pretty limited time for hobby projects at the moment, but I might get around to playing with this again in the next... few months?

Thanks again for contributing to this project!

**Comment by libesz** [comment]
No issues! Tried to address all the comments. I decided to keep the 0.0 - 1.0 range, but feel free to suggest improvements to the doc text.

**Comment by JordanAceto** [comment]
Cool, thanks again for working on this!

**Comment by libesz** [comment]
Thanks!
Would you mind to release a new version of the crate when you have a chance?

**Comment by JordanAceto** [comment]
> Thanks! Would you mind to release a new version of the crate when you have a chance?

Yes I'll get to this in a couple days or so, cheers

**Comment by JordanAceto** [comment]
That was more that a couple days, but I just published 0.2.0 with your new changes, thanks again!

**Comment by libesz** [comment]
No worries 👍 . Thanks!

**Pull request merged**
